#deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: icici-deployment
  labels:
    app: icici
spec:
  replicas: 2
  selector:
    matchLabels:
      app: icici
  template:
    metadata:
      labels:
        app: icici
    spec:
      containers:
      - name: icici-cont
        image: rojakumaridocker/icici-project-money-transfer:version
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
